import { source_sans } from "./ui/fonts";

export const metadata = {
    title: "Next.js",
    description: "Generated by Next.js",
};

export default function Layout({ children }: { children: React.ReactNode }) {
    return (
        <html lang="en">
            <body
                className={`${source_sans.className} antialiased max-w-screen-2xl mx-auto`}>
                {children}
            </body>
        </html>
    );
}
